"""Tokens

Revision ID: 1888746a7eb3
Revises: ef1a7a8e0e70
Create Date: 2023-03-16 20:38:42.275062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1888746a7eb3'
down_revision = 'ef1a7a8e0e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('API_Token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('API_Expiration', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['API_Token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('API_Expiration')
        batch_op.drop_column('API_Token')

    # ### end Alembic commands ###
