"""Initial3

Revision ID: 8d5cd1e26793
Revises: 98a0cc8b6337
Create Date: 2023-02-20 18:46:15.629739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d5cd1e26793'
down_revision = '98a0cc8b6337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_dos', schema=None) as batch_op:
        batch_op.drop_constraint('to_dos_ibfk_2', type_='foreignkey')
        batch_op.drop_column('Owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_dos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Owner', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('to_dos_ibfk_2', 'users', ['Owner'], ['ID_User'])

    # ### end Alembic commands ###
